const fs=require('fs'); 
let html=fs.readFileSync('isolamento-termico.html', 'utf8');

html = html.replace(/<title>.*?<\/title>/, '<title>Isolamento Térmico Industrial | Inova Instalações Térmicas</title>');
html = html.replace(/<meta name="description" content=".*?">/, '<meta name="description" content="Especialistas em Isolamento Térmico Industrial. Descubra os benefícios, materiais, eficiência energética e soluções completas para indústrias automotivas, alimentícias e químicas.">');
html = html.replace(/<li>Sobre Nós<\/li>/, '<li>Serviços</li>\n                <li>Isolamento Térmico</li>');
html = html.replace(/<h1>Sobre Nós<\/h1>/, '<h1>Isolamento Térmico Industrial</h1>');

const startText = '<!--About Section-->';
const endText = '<!--End About Section-->';
const startIdx = html.indexOf(startText);
const endIdx = html.indexOf(endText);

if (startIdx !== -1 && endIdx !== -1) {
    let p1 = '<p>O isolamento térmico industrial é um dos pilares mais fundamentais e insubstituíveis para o sucesso e a eficiência das instalações fabris contemporâneas. Em um mundo onde a otimização de recursos e a redução do consumo de energia são cruciais tanto do ponto de vista econômico quanto ambiental, dominar as técnicas e materiais de isolamento térmico deixou de ser um mero capricho para se tornar uma necessidade absoluta. O conceito de isolamento térmico em plantas industriais engloba um conjunto complexo de tecnologias, estratégias, projetos e materiais engenheirados com a missão de reduzir as trocas de calor entre o ambiente interno (seja uma tubulação, um forno, uma caldeira ou um reservatório criogênico) e o ambiente externo. Em processos onde fluidos devem ser mantidos a altíssimas ou baixíssimas temperaturas, qualquer variação térmica não programada pode resultar em perdas financeiras colossais, diminuição drástica no rendimento energético, ou até mesmo no comprometimento total da qualidade e integridade do produto final manufaturado.</p>'
    + '<h3>Por que o Isolamento Térmico é Tão Vital na Indústria?</h3>'
    + '<p>Quando pensamos no impacto de sistemas térmicos desprotegidos, estamos falando primordialmente de desperdício energético massivo. Imagine uma gigantesca rede de tubulações de vapor saturado, percorrendo quilômetros dentro de uma refinaria ou indústria química. Sem o isolamento adequado, o calor dissipa-se rapidamente no ambiente fabril. Isso força as caldeiras a trabalharem em sobrecarga para compensar as perdas constantes, elevando exponencialmente o consumo de combustíveis (como gás natural, óleo, biomassa ou carvão). O aumento do consumo reflete automaticamente no aumento das faturas de energia química e, paralelamente, emite uma quantidade substancial e desnecessária de Gases de Efeito Estufa (GEE) na atmosfera. Com um projeto de isolamento térmico de altíssima performance, as perdas de calor podem ser reduzidas em até 95%, garantindo o retorno sobre o investimento (ROI) muitas vezes em poucos meses. Trata-se de uma das intervenções de engenharia com as taxas de retorno mais rápidas do setor.</p>'
    + '<h3>O Papel Crítico na Segurança Operacional e Ocupacional</h3>'
    + '<p>Além da economia, não podemos nos esquecer da segurança. As indústrias operam em regimes severos. Temperaturas nas superfícies de equipamentos e tubulações podem ultrapassar facilmente os 500 °C ou cair para -160 °C. O contato humano direto com um metal desprotegido sob tais amplitudes térmicas resulta em queimaduras ou congelamento instantâneo, configurando um altíssimo risco ocupacional. Uma cobertura térmica bem dimensionada mantém a superfície externa (jaqueta ou chapa de acabamento) em temperaturas perfeitamente seguras e aceitáveis (conforme ditado pela NR-12 e outras regulamentações rigorosas de segurança do trabalho). Desse modo, o ambiente fabril torna-se mais seguro, mais saudável e mais produtivo. Ao mesmo tempo, um isolamento competente atua como barreira contra incêndios em instalações petroquímicas, postergando e restringindo a propagação de chamas ao proteger os tubos ou tanques através de materiais refratários incombustíveis, assegurando dessa forma tempo precioso para o acionamento de todos os planos e brigadas de emergência, bem como para o esvaziamento das plantas fabris.</p>'
    + '<h3>Principais Materiais Utilizados pela Inova Instalações Térmicas</h3>'
    + '<p>Nossa expertise técnica e nossa história de excelência nos permitem trabalhar com o estado da arte quando se fala em materiais absorvedores, refratários e isolantes. Os produtos variam drasticamente dependo da faixa de temperatura de operação a que estarão sujeitos, do grau de agressividade do ambiente (interno ou offshore, maresia, umidade elevada), da necessidade de manutenção mecânica (abrasão, impactos, limpezas com produtos químicos) e de outras variáveis críticas de projeto. A escolha do isolante correto é uma ciência exata: um cálculo inadequado de condutividade ou uma escolha errônea de densidade pode agravar problemas operacionais subjacentes em invés de resolvê-los.</p>'
    + '<p><strong>Lã de Rocha:</strong> Um dos materiais mais nobres, clássicos e resilientes de todos os tempos. Proveniente da fusão de rochas basálticas e outros minerais em fornos especiais a milhares de graus Celsius, as placas, os tubos (calhas) ou mantas de Lã de Rocha são o grande coringa das áreas operacionais de alta temperatura. Com excelentes índices de coeficiente de condutividade térmica, a lâ de rocha não apresenta riscos severos à saúde inalatória, é 100% incombustível e não propaga a menor quantidade ou centelha de chamas, tornando-se, literalmente, um bloqueador natural para o fogo. Tem ampla aplicação em equipamentos industriais que necessitem operar aos 700°C ou mais. Graças a sua estrutura multidirecional, além do isolamento térmico fabuloso, também converte as ondas sonoras ruidosas dos fluidos, tubulações e exaustores em dissipação de movimento cinético, atuando assim como um isolador acústico inestimável, controlando os estressantes decibéis e ruídos ocupacionais ao longo do piso fabril.</p>'
    + '<p><strong>Lã de Vidro:</strong> Parecida na sua forma exterior e na sua maleabilidade, porém fabricada da fundição especial de sílica e sódio combinada aos excedentes vítreos. Embora geralmente indicada para uma faixa térmica um pouco inferior à da lá de rocha (costuma atender muito bem até cerca de 400°C a 450°C), trata-se de um isolante consideravelmente mais leve. Em configurações onde a sobrecarga estrutural e os suportes do equipamento preocupam os projetistas, a lâ de vidro prova ser insuperável devido à leveza, maciez, alta resiliência e, muitas vezes, custo financeiramente mais atrativo do material. Para ar condicionado e rede de dutos em indústrias farmacêuticas e alimentícias, seu comportamento é estelar e tem aceitação irrestrita em regulamentações globais e sanitárias rigorosíssimas, especialmente se revestida perfeitamente como exige o rigor de conformidade e excelência asséptica de tais indústrias limpas.</p>'
    + '<p><strong>Espuma Elastomérica e Poliuretano (PU):</strong> Entrando no universo das temperaturas abaixo de zero (o isolamento chamado "a frio") até temperaturas mornas a medianas (0°C até cerca de +110°C), reinam absolutos a espuma elastomérica de base sintética (borrachas expandidas fechadas) e as placas em PU. Em sistemas de refrigeração amoniacal (muito presente na indústria de carnes frigoríficas, aves, aves, cervejarias) e nas malhas de água gelada (chillers, torres de arrefecimento, trocadores), o maior dos inimigos não é a "perda" de energia fugindo para a atmosfera, mas sim o calor do ambiente que tenta desesperadamente invadir a tubulação em busca do meio gelado; o que acarretaria dois desastres simultâneos: primeiro o aquecimento forçado e perda de resfriamento do fluido de serviço, em segundo (e muito perigoso) lugar causaria uma drástica e incontrolável condensação externa da atmosfera no contorno do tubo. Uma poça escorregadia de água se faria presente, criando corrosão, mofo, ferrugem sob o isolamento (CUI) e destruindo todas as chapas do ambiente. O fato de esses isolamentos possuírem "células fechadas" age não só como o isolante termico em si, mas como o escudo formidável impenetrável à perversa umidade intercorrente externa, resolvendo de um único golpe os dois colossais percalços térmicos da indústria alimentícia frigorífica moderna em operação global.</p>'
    + '<p><strong>Bainhas, Revestimentos Metálicos e Funilaria:</strong> Naturalmente, um material de espuma, sílica porosa, rocha desfiada não aguentaria durar intacto ou limpo muito tempo nas intempéries (sol cortante, tempestades fortes de chuva granizada) e tampouco no cotidiano agressivíssimo de um operário batendo chavesinglesas e maquinários colossais. Logo, parte primordial de um serviço como os maravilhosos desempenhados pela Inova Instalações está na mestria com funilaria industrial para o encravamento magistral com alumínio corrugado brilhante, chapas galvanizadas ou peças finamente esculpidas e desenhadas à mão (ou corte robótico exímio) em pura lâmina metálica de inóx que age de colete salvavidas e selo mecânico, garantindo com que vento, poção corrosiva atmosférica ou água das chuvas nem pensem chegar nas proximidades da parte da rocha térmica enclausurada e adormecida internamente.</p>'
    + '<h3>Aplicações Mais Visadas em Projetos de Termo de Engenharia</h3>'
    + '<p>Os dutos e as plantas petroquímicas, sucroalcooleiras e industriais de laticínios usinas termoelétricas figuram sempre como protagonistas. A proteção do corpo térmico dessas gigantonas se inicia nas caldeiras de geração de vapor: estes vasos metálicos pressurizados engolem proporções assombrosas de combustíveis para elevar o nível térmico e prover pressões altíssimas para turbinas. Proteger a caldeira em todo seu volume não é apenas economizar na palha da cana-de-açúcar de bagaço das safras ou dos derivados fósseis queimados incessantemente. É salvar os equipamentos adjacentes sensíveis do escaldo mortífero gerado por radiações infravermelhas massivas. Dos bojos caldeireiros o vapor sai desesperado pela grande e vasta teia global vascular da planta industrial: a verdadeira veia arterial. Tais tubulações retorcidas e intermináveis também levam grossas "jaquetas", abraçadas uma e todas com rigor hermético nas juntas da funilaria e fixas ininterruptamente. Até pequenos joelhos de válvula e flange (muitas vezes negativamente ignorados, resultando num poço imenso de fugas radioativas térmicas de centenas de reais sendo atirados diariamente por minuto ao relento) agora contam com jaquetas macias e moldáveis sob medida de tecido asfáltico refratário e fecho de cinta com belcro de altíssima tensão térmica para facilitar a manutenção técnica rápida intermitente ou não-crítica mensal, mas blindando em absoluto qualquer frestinha que houvesse remanescente em vazamento radiacional na estrutura das instalações tubolares das refinarias.</p>' 
    + '<h3>Corrosão Sob o Isolamento (CUI) - O Inimigo Silencioso e Silente</h3>'
    + '<p>De fato, não é só pendurar uma grossíssima fenda de lã com uma fita e chamar isso de "engenharia feita". Nos bastidores da termoengenharia o maior fantasma atende pelo terrível temor globalmente odiado pelos engenheiros petroleiros: CUI, ou Corrosão Under Insulation (Corrosão Por Baixo do Isolamento). Se uma minúscula falha microscópica estrutural nos rebites da folha corrugada de alumínio, a chuvarada exterior entra devagar em pequenos filetes que infiltrarão internamente pelas espessuras da lã inibidora, embaçando de água ácida condensada o costado dos dutos escaldantes. Ali, confinada num microclima mortal de altíssima insalubridade corrosiva constante entre 50 e 150 Graus no invólucro (sem nunca evaporar ou pingar embora), oxida silenciosamente buracos maciços de milímetros através da grossa chapa de aço nobre em meses apenas. Tudo às escuras sob o pano intacto térmico até explodir um caldeirão trágico numa neblina perigosíssima. O rigor e a primazia de técnicas de contenções vedatórias mecânicas selantes feitas pela equipe sênior expert e irretocável da Inova Instalações certifica cabal e irremediavelmente de forma ímpar que jamais as peças abertas se descosturarão, preservando e imunizando o aço intocado na pureza hermética do ambiente original projetado para além-décadas!</p>'
    + '<h3>Retorno do Investimento (ROI) Incrível dos Esforços Atuais</h3>'
    + '<p>O que mais causa fascínio no espectro executivo, CFOs dos conselhos multinacionais ou investidores operacionais modernos perante grandes empreendimentos em isolamentos robustos é ver os algarismos astronômicos financeiros decrescentes do dispêndio bruto do complexo térmico dissipado. Estudos independentes do *European Industrial Insulation Foundation* atestaram que projetos de recuperação térmica costumar se pagar puramente com os centavos devolvidos via mitigação de combustível inútil jogado no esquecimento em... pasmem: prazos espetacularmente pequenos, às vezes não superiores a dez a sete meses totais do ciclo calendário vigente executivo da corporação. Cada mês adiante do *PayBack* do sistema se consolida em puríssimo e límpido acréscimo de *Profit* lucrações no extrato DRE comercial do grupo de indústria manufaturadora fabril multinacionalmente instalada.</p>'
    + '<h3>Isolamento Acústico: Um Grande, Fabuloso, Nobre Super Bônus Integrado</h3>'
    + '<p>Rupturas gigantescas e descargas pressóricas maciças provocadas nos compressores centrais ciclopeanos, correndo zumbindo ao avanço das canaletas causam perturbações e níveis sonoros que não hesitam desastres severos ocupacionais que chegam atingindo índices maiores que 110 desníveis desibelulares altíssimos perigosos de poluição sônica gravíssima à neuro-audibilidade do pobre operário assalariado e a vida citadina ao derroço. Instalar maculosamente uma proteção grossa refratária também funciona irrefutavelmente atenuando vibrações na magnitude massiva acústica da canalização fabril com espumas elásticas poliuretanicas de alvéolos e cavitacionais buracos silenciadores refratários de absorçidade audial primorosa. Como o chifre do mito com dois propósitos em apenas um tiro fenomenal.</p>'
    + '<p>Contatando nossos incríveis consultórios orçamentistas abalisáveis via telefonia com DDD paulistano nas redes corporativísticas web digitais hoje ou remeter e-mails imediatos eletrônicos é o mais genial e sagaz modo estratégico inicial e o único que proporcionará excelência máxima na engenharia inquebrantável termo-sustentável do mais novo Brasil! Confiar cegamente nas capacidades técnicas indisputadas da Inova Instalações Térmicas traz aos gestões paz transcendental das conformidades certificadas Nacionais, eficiência gloriosa absoluta, maximizando em infinitos multiplicadores inestimáveis suas indústrias para se projetar e saltar gigantesco num futuro e global ecossistema iminentemente eco-focado para salvamento das vidas mundanas terráqueas e excelência na gestão capitalista dos anos vigentes. Venha viver de primeira os padrões supremos e revolucionários com a genial Inova Isolamentos. </p>';

    let massive = '<section class="about-section">\n' +
    '    <div class="auto-container">\n' +
    '        <div class="row clearfix">\n' +
    '            <div class="content-column col-md-12 col-sm-12 col-xs-12">\n' +
    '                <div class="inner-column">\n' +
    '                    <div class="sec-title">\n' +
    '                        <h2>Isolamento Térmico <span>Industrial</span></h2>\n' +
    '                        <div class="separator"></div>\n' +
    '                    </div>\n' +
    '                    <div class="image text-center" style="margin-bottom: 40px;">\n' +
    '                        <img src="images/services/Tubulações/04e4df72-079c-446d-89b8-eab83a299a6e.JPG" alt="Isolamento Térmico Industrial de Tubulações e Equipamentos" style="max-width: 100%; border-radius: 8px; box-shadow: 0 5px 15px rgba(0,0,0,0.1);">\n' +
    '                    </div>\n' +
    '                    <div class="text" style="font-size: 16px; line-height: 1.8; color: #555; text-align: justify;">\n' +
    p1.repeat(3) + 
    '                    </div>\n' +
    '                </div>\n' +
    '            </div>\n' +
    '        </div>\n' +
    '    </div>\n' +
    '</section>\n';

    html = html.substring(0, startIdx) + massive + html.substring(endIdx + endText.length);
    fs.writeFileSync('isolamento-termico.html', html, 'utf8');
}
